[package]
name = "chess-master"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true

[dependencies]
rand = "0.9.0"
